workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

default:
  tags:
    - docker

stages:
  - build
  - publish

gitlab-ci-daqlite-build:
  stage: build
  image: registry.esss.lu.se/ecdc/ess-dmsc/build-nodes/ubuntu2204-qt6:1.1
  script:
      - mkdir -p build
      - cd build
      - conan remote add --insert 0 --force ecdc-conan-external https://artifactory.esss.lu.se/artifactory/api/conan/ecdc-conan-external
      - conan install ..
      - cmake ..
      - make
  artifacts:
    paths:
      - build/bin
      - build/lib
      - build/licenses
    expire_in: 1 week

gitlab-ci-daqlite-publish-docker-image:
  stage: publish
  image: docker:28-cli
  script:
    - |
      docker login \
        -u "$CI_REGISTRY_USER" \
        -p "$CI_REGISTRY_PASSWORD" \
        "$CI_REGISTRY"
    - |
      docker build \
          --build-arg https_proxy="http://172.20.72.11:8888" \
          --build-arg http_proxy="http://172.20.72.11:8888" \
          -t registry.esss.lu.se/ecdc/ess-dmsc/daqlite:$DOCKER_IMAGE_TAG \
          -f .ci/docker/Dockerfile.deploy .
    - docker push registry.esss.lu.se/ecdc/ess-dmsc/daqlite:$DOCKER_IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DOCKER_IMAGE_TAG: "latest"
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_IMAGE_TAG: "${CI_COMMIT_TAG}"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never

gitlab-ci-daqlite-publish-to-artifactory:
  stage: publish
  image: alpine/curl:latest
  dependencies:
    - gitlab-ci-daqlite-build
  before_script:
    - curl -fL https://install-cli.jfrog.io | sh
    - jf config add $ESS_ARTIFACTORY_ID --url=$ESS_ARTIFACTORY_URL --user=$ESS_ARTIFACTORY_ECDC_USER --password=$ESS_ARTIFACTORY_ECDC_GENERIC_TOKEN
    - jf config show
  script:
    - mkdir -p archive/daqlite-ubuntu2204
    - cp -r build/bin archive/daqlite-ubuntu2204
    - cp -r build/lib archive/daqlite-ubuntu2204
    - cp -r scripts archive/daqlite-ubuntu2204
    - cp -r configs archive/daqlite-ubuntu2204
    - tar czvf daqlite-ubuntu2204.tar.gz -C archive daqlite-ubuntu2204
    - jf rt u --build-name="daqlite-ubuntu2204" --build-number=${CI_JOB_ID} daqlite-ubuntu2204.tar.gz ecdc-generic-release/${ARTIFACTORY_UPLOAD_PATH}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        ARTIFACTORY_UPLOAD_PATH: "${CI_PROJECT_NAME}/${CI_DEFAULT_BRANCH}/${CI_PIPELINE_IID}/"
    - if: $CI_COMMIT_TAG
      variables:
        ARTIFACTORY_UPLOAD_PATH: "${CI_PROJECT_NAME}/tags/${CI_COMMIT_TAG}/"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
